### ISSUE TITLE
FlxMenu - Uncaught Exception - While calling goto method

### ISSUE THREAD

**Issue by cooljith91112** [john32b/djFlixel#17]
I have a simple menu like below

```haxe
var menu = new FlxMenu(32, 32, 100, 5);
menu.createPage("main").addM(["New Game|link|new_game", "Options|link|@options", "Quit|link|#quit|cfm=:yes:no"]);
add(menu);
menu.goto('main');
```
whenever I try to run my project, the application crashes with the following error, (the demo project is running perfectly fine though)
```
RAW-HAXE.js:13755 Uncaught TypeError: Cannot read properties of null (reading 'tweenAr')
    at djFlixel_ui_menu_MPage.clear_tween_slot (RAW-HAXE.js:13755:19)
    at djFlixel_ui_menu_MPage.setDataSource (RAW-HAXE.js:13189:8)
    at djFlixel_ui_menu_MPage.setPage (RAW-HAXE.js:14726:8)
    at djFlixel_ui_FlxMenu.pool_get (RAW-HAXE.js:12891:5)
    at djFlixel_ui_FlxMenu._on_pageActive (RAW-HAXE.js:12848:24)
    at djFlixel_ui_FlxMenu.goto (RAW-HAXE.js:12673:9)
    at PlayState.create (RAW-HAXE.js:4765:8)
    at flixel_FlxGame.switchState (RAW-HAXE.js:19997:15)
    at flixel_FlxGame.update (RAW-HAXE.js:20034:9)
    at flixel_FlxGame.step (RAW-HAXE.js:20025:8)
```
It only happens when the `goto` method is invoked.

- Haxe 4.2.5
- Flixel 4.11.0
- lime 7.9.0
- OpenFL 9.1.0

**Comment by cooljith91112** [comment]
My bad. Forgot to call the `init` method. Working fine now. LOL.
